CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    xp INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    difficulty VARCHAR(255) NOT NULL,
    context VARCHAR(2000) NOT NULL,
    expected_output_format VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE challenge_requirements (
    challenge_id BIGINT NOT NULL,
    requirement VARCHAR(500) NOT NULL,
    CONSTRAINT fk_requirement_challenge FOREIGN KEY (challenge_id) REFERENCES challenges(id)
);

CREATE TABLE challenge_constraints (
    challenge_id BIGINT NOT NULL,
    constraint_text VARCHAR(500) NOT NULL,
    CONSTRAINT fk_constraint_challenge FOREIGN KEY (challenge_id) REFERENCES challenges(id)
);

CREATE TABLE challenge_acceptance_criteria (
    challenge_id BIGINT NOT NULL,
    criterion VARCHAR(500) NOT NULL,
    CONSTRAINT fk_criterion_challenge FOREIGN KEY (challenge_id) REFERENCES challenges(id)
);

CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    challenge_id BIGINT NOT NULL,
    answer VARCHAR(10000) NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_submission_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_submission_challenge FOREIGN KEY (challenge_id) REFERENCES challenges(id)
);

CREATE TABLE evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    requirement_understanding DOUBLE PRECISION NOT NULL,
    logical_clarity DOUBLE PRECISION NOT NULL,
    technical_feasibility DOUBLE PRECISION NOT NULL,
    edge_case_coverage DOUBLE PRECISION NOT NULL,
    communication_structure DOUBLE PRECISION NOT NULL,
    final_score DOUBLE PRECISION NOT NULL,
    feedback VARCHAR(5000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_evaluation_submission UNIQUE (submission_id),
    CONSTRAINT fk_evaluation_submission FOREIGN KEY (submission_id) REFERENCES submissions(id)
);
